server:
  port: 8862
dubbo:
  application:
    name: dubbo-provider
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: nacos://192.168.31.242:8848
  consumer:
    timeout: 4000
spring:
  main:
    allow-bean-definition-overriding: true